# Generated by Django 5.0.3 on 2024-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_alter_post_options_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_like',
            field=models.PositiveIntegerField(default=1, verbose_name='лайки'),
            preserve_default=False,
        ),
    ]
